### ISSUE TITLE
Scraping bbc good food

### ISSUE THREAD

**Issue by rabol** [ssnepenthe/recipe-scraper#47]
Hi

Just as a test I tried to scrape: https://www.bbcgoodfood.com/recipes/overnight-oats

It actually worked pretty well.
instructions, url, cooktime, nutrition and yield was missing :)

My question is: how do I figure out which scraper was used, so that I can adjust it to fetch the last bits?

**Comment by ssnepenthe** [comment]
The ScraperResolver class is used to get the first scraper instance that supports a given crawler. Unfortunately, the resolver is a protected prop on the DelegatingScraper class.

As long as it it is just for debugging purposes you can probably grab the resolver using reflection - something like:

```php
$scraper = RecipeScraper\Factory::make();
$prop = new ReflectionProperty($scraper, 'resolver');
$prop->setAccessible(true);
$resolver = $prop->getValue($scraper);

$scraper = $resolver->resolve($crawler);
```

Or just manually create it using the same order as used in the Factory::makeDelegatingScraperInstance method.

Maybe in a future release I will add a getter for the resolver to simplify this process.

---

After a quick look, the SchemaOrgJsonLd class is used for this site.

* Instructions are missed because we are accounting for strings and array of strings but BBC good food uses an array of HowToStep objects. This should be an easy fix.
* URL is not present in the JSON+LD data - we could probably fall back to the canonical link.
* Cooktime is not present for this recipe.
* We are not collecting nutrition data for any recipes, but it might be a nice addition.
* I think yield is missed because it is given as an integer but we are assuming a numeric string. Should also be an easy fix.

If you want to submit a pr for any of the above that would be great, otherwise i will try to make some updates in the next couple of days.

**Comment by rabol** [comment]
I have added a few small thing to my local version
I have also added the nutrition property

Will see if I can do a PR soon
